# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- dev

pool:
  vmImage: ubuntu-latest

name: aeroclub-scs-booking-portal

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'npm install'
  workingDirectory: '$(Build.SourcesDirectory)'

- task: AzureStaticWebApp@0
  inputs:
      app_location: "/" 
      api_location: "api"
      app_build_command: $(build_command)
      output_location: "dist"
  env:
      azure_static_web_apps_api_token: $(deployment_token)